version: "3"

volumes:
  nfcore_stats_data: {}

services:
  nfcore_redis:
    container_name: nfcore_stats_redis
    image: "redis:latest"
    ports:
      - "127.0.0.1:6379:6379"

  nfcore_stats_db:
    container_name: nfcore_stats_db
    image: "questdb/questdb:latest"
    volumes:
      - nfcore_stats_data:/root/.questdb/db
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8812:8812"
    env_file:
      - .env

  nfcore_stats_api:
    container_name: nfcore_stats_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - nfcore_stats_scheduler
      - nfcore_stats_db
    restart: always
    volumes:
      - ./backend:/mnt/backend
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    command: /mnt/backend/run/start_api.sh

  nfcore_stats_scheduler:
    container_name: nfcore_stats_scheduler
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - nfcore_redis
    volumes:
      - ./backend:/mnt/backend
    env_file:
      - .env
    command: /mnt/backend/run/start_scheduler.sh
